version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: f1-springboot-app
    depends_on:
      - db
    environment:
      DB_HOST: ${APP_DB_HOST}
      DB_PORT: ${APP_DB_PORT}
      DB_NAME: ${APP_DB_NAME}
      DB_USERNAME: ${APP_DB_USERNAME}
      DB_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
