logging:
  level:
    root: DEBUG
    com.elkhami.f1_champions: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.github.resilience4j: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG